dotnet build open-api-8
dotnet build open-api-9
dotnet build open-api-10
dotnet build open-api-11
dotnet build redirect-http-result-is-local-url
dotnet build sse-2
dotnet build sse-3
dotnet build sse-4
dotnet build validation-1
dotnet build validation-2
dotnet build validation-3
