#!/bin/bash
dotnet build hello-world
dotnet build backend-patch-signals
dotnet build backend-patch-signals-2
dotnet build backend-patch-signals-3
dotnet build backend-patch-signals-4
dotnet build data-attr
dotnet build data-bind
dotnet build data-class
dotnet build data-compute
dotnet build data-effect
dotnet build data-on-click
dotnet build data-on-custom-event
dotnet build data-on-interval
dotnet build data-show
dotnet build data-style
dotnet build data-indicator
dotnet build data-on-signal-patch
dotnet build data-on-signal-patch-filter
dotnet build data-ignore
