#!/bin/bash
dotnet build Component
dotnet build ComponentEight
dotnet build ComponentEighteen
dotnet build ComponentEleven
dotnet build ComponentFifteen
dotnet build ComponentFive
dotnet build ComponentFour
dotnet build ComponentFourteen
dotnet build ComponentNine
dotnet build ComponentNineteen
dotnet build ComponentSeven
dotnet build ComponentSeventeen
dotnet build ComponentSix
dotnet build ComponentSixteen
dotnet build ComponentTen
dotnet build ComponentThirteen
dotnet build ComponentThree
dotnet build ComponentTwelve
dotnet build ComponentTwenty/Web
dotnet build ComponentTwentyFive
dotnet build ComponentTwentyFour
dotnet build ComponentTwentyOne/Web
dotnet build ComponentTwentySeven
dotnet build ComponentTwentySix
dotnet build ComponentTwentyThree
dotnet build ComponentTwentyTwo/Web
dotnet build ComponentTwo
dotnet build DataBinding
dotnet build DataBindingTwo
dotnet build HelloWorld
dotnet build QuickGridOne
dotnet build RadioButton
dotnet build RenderFragment
